version: '3.8'

services:
  server:
    build: ./server
    ports:
      - "5053:5053"
    volumes:
      - ./server:/app
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/shortener
      - NEXT_PUBLIC_API_URL=http://server:5053

  client:
    build: ./client
    ports:
      - "3000:3000"
    # volumes:
    #   - ./client:/app
    depends_on:
      - server
    environment:
      - NEXT_PUBLIC_API_URL=http://server:5053

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: shortener
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: